# docs.serverless.com
service: test-sns

provider:
  name: aws
  runtime: nodejs4.3
  stage: dev
  region: ap-southeast-2

# you can add statements to the Lambda function's IAM Role here
#  iamRoleStatements:
#    - Effect: "Allow"
#      Action:
#        - "s3:PutObject"
#      Resource:
#        Fn::Join:
#          - ""
#          - - "arn:aws:s3:::"
#            - "Ref" : "ServerlessDeploymentBucket"

# you can add packaging information here
#package:
#  exclude:
#    - exclude-me.js
#  artifact: my-service-code.zip

functions:
  hello:
    handler: handler.hello
    events:
      - sns: greeter-topic
#      - http:
#          path: users/create
#          method: get
#      - s3: ${env:BUCKET}
#      - schedule: rate(10 minutes)
#      - stream: arn:aws:dynamodb:region:XXXXXX:table/foo/stream/1970-01-01T00:00:00.000

# you can add CloudFormation resource templates here
resources:
  Resources:
    GreetingsBucketResource:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: greeter-bucket
        NotificationConfiguration:
          TopicConfigurations:
            - Event: 's3:ObjectCreated:*'
#              Filter:
#                S3Key:
#                  Rules:
#                    - Name: 'Prefix'
#                      Value: 'in/'
#                    - Name: 'Suffix'
#                      Value: '.tar'
              Topic:
                Ref: 'SNSTopicGreetertopic'
    GreetingsBucketIamPolicy:
      Type: AWS::SNS::TopicPolicy
      DependsOn: GreetingsBucketResource
      Properties:
        PolicyName: greeter-bucket-sns
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - sns:Publish
#              Resource: 
#                Ref: 'SNSTopicGreetertopic'
#              Principal:
#                AWS: "*"
#              Condition:
#                AnrLike:
#                  'aws:SourceArn': 'arn:aws:s3:*:*:greeter-bucket'
        Topics:
          - Ref: 'SNSTopicGreetertopic'
            

#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"
